/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package streamcorpus_v3;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * General purpose flags. These flags can be used to mark documents as
 * meeting an extensible set of criteria.
 */
public enum FlagType implements org.apache.thrift.TEnum {
  PROFILE(0);

  private final int value;

  private FlagType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FlagType findByValue(int value) { 
    switch (value) {
      case 0:
        return PROFILE;
      default:
        return null;
    }
  }
}
